#!/bin/sh -e
# Set up audio from NFC system
export AUDIO_LOG_FILE=/tmp/audio.log
if [ -f $AUDIO_LOG_FILE ]; then
    printf "Removing audio file %s\n" "$AUDIO_LOG_FILE"
    sudo rm $AUDIO_LOG_FILE
fi

printf "I am user: %s\n" "$USER"

# Connect to the bluetooth speaker
#bluetoothctl connect B0:1F:81:3F:E6:3E


/usr/bin/python3.7 /home/pi/Projects/nfc_audio/audio_control_app.py -s 5 -f $AUDIO_LOG_FILE &


#@reboot /home/pi/Projects/nfc_audio/scripts/nfc_audio_start >> >> /tmp/cron.log
